-- ============================================================================
-- Trading Bot Database Schema - SQLite
-- Version: 1.0
-- Description: Schema for Pro Trader Rule-Based Decision Tree System
-- Timeframes: 1D (trend), 4H (entry timing)
-- ============================================================================

-- ============================================================================
-- 1. STOCK PRICES TABLE
-- ============================================================================
-- Stores raw OHLCV price data for both 1D and 4H timeframes

CREATE TABLE IF NOT EXISTS stock_prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,              -- Stock symbol (e.g., 'VNM', 'VCB')
    timeframe TEXT NOT NULL,           -- '1D' or '4H'
    timestamp INTEGER NOT NULL,        -- Unix timestamp (UTC)
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    
    -- Prevent duplicate data
    UNIQUE(symbol, timeframe, timestamp)
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_prices_symbol_time 
    ON stock_prices(symbol, timeframe, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_prices_timestamp 
    ON stock_prices(timestamp DESC);

-- ============================================================================
-- 2. INDICATORS TABLE
-- ============================================================================
-- Stores calculated technical indicators for Pro Trader strategy

CREATE TABLE IF NOT EXISTS indicators (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    timestamp INTEGER NOT NULL,
    
    -- Trend Indicators (Layer 1: Xác định xu hướng)
    ma_200 REAL,                       -- Moving Average 200 (trend)
    ema_20 REAL,                       -- Exponential MA 20 (short-term trend)
    trend_direction TEXT,              -- 'UP', 'DOWN', 'SIDEWAYS'
    trend_strength REAL,               -- 0-100 (distance from MA)
    
    -- Momentum Indicators (Layer 2: Kiểm tra động lượng)
    rsi_14 REAL,                       -- RSI period 14
    rsi_signal TEXT,                   -- 'OVERSOLD', 'NEUTRAL', 'OVERBOUGHT'
    macd_line REAL,                    -- MACD line
    macd_signal REAL,                  -- MACD signal line
    macd_histogram REAL,               -- MACD histogram
    macd_trend TEXT,                   -- 'BULLISH', 'BEARISH', 'NEUTRAL'
    
    -- Volatility Indicators (Layer 4: Tìm điểm vào)
    bb_upper REAL,                     -- Bollinger Band upper
    bb_middle REAL,                    -- Bollinger Band middle (SMA 20)
    bb_lower REAL,                     -- Bollinger Band lower
    bb_width REAL,                     -- BB width (volatility measure)
    bb_position REAL,                  -- Price position in BB (0-1)
    
    -- Volume Analysis (Layer 3: Xác nhận bằng dòng tiền)
    volume_ma_20 REAL,                 -- Volume MA 20
    volume_ratio REAL,                 -- Current volume / MA volume
    volume_signal TEXT,                -- 'HIGH', 'NORMAL', 'LOW'
    
    -- Support/Resistance Levels
    support_level REAL,                -- Dynamic support
    resistance_level REAL,             -- Dynamic resistance
    distance_to_support_pct REAL,      -- % distance to support
    distance_to_resistance_pct REAL,   -- % distance to resistance
    
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    
    UNIQUE(symbol, timeframe, timestamp),
    FOREIGN KEY (symbol, timeframe, timestamp) 
        REFERENCES stock_prices(symbol, timeframe, timestamp)
        ON DELETE CASCADE
);

-- Indexes for fast queries and filtering
CREATE INDEX IF NOT EXISTS idx_indicators_symbol_time 
    ON indicators(symbol, timeframe, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_indicators_rsi 
    ON indicators(rsi_14) WHERE rsi_14 IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_indicators_trend 
    ON indicators(trend_direction, timeframe);

-- ============================================================================
-- 3. SIGNALS TABLE
-- ============================================================================
-- Stores trading signals generated by the decision tree

CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,           -- Timeframe used for signal generation
    timestamp INTEGER NOT NULL,        -- When signal was generated
    
    -- Signal Classification
    signal_type TEXT NOT NULL,         -- 'STRONG_BUY', 'WEAK_BUY', 'WATCH', 'SELL', 'NO_ACTION'
    confidence_score REAL,             -- 0-100 (composite score)
    strategy_name TEXT,                -- Name of strategy combination used
    
    -- Decision Tree Reasoning (JSON format)
    reasoning TEXT,                    -- JSON: {"ma200": "UP", "ema20": "UP", "rsi": 45, ...}
    conditions_met TEXT,               -- JSON: ["trend_up", "rsi_neutral", "volume_high"]
    
    -- Price Context
    price_at_signal REAL NOT NULL,
    
    -- Risk Management Parameters
    suggested_stop_loss REAL,          -- Suggested stop-loss price
    suggested_take_profit REAL,        -- Suggested take-profit price
    position_size_pct REAL,            -- % of capital to invest (e.g., 5%)
    risk_reward_ratio REAL,            -- Risk/Reward ratio
    
    -- Execution Tracking
    is_executed BOOLEAN DEFAULT 0,     -- Has order been executed?
    executed_at INTEGER,               -- Execution timestamp
    execution_price REAL,              -- Actual execution price
    execution_notes TEXT,              -- Execution details/issues
    
    -- Position Lifecycle
    is_closed BOOLEAN DEFAULT 0,       -- Has position been closed?
    closed_at INTEGER,                 -- Close timestamp
    close_price REAL,                  -- Close price
    close_reason TEXT,                 -- 'TAKE_PROFIT', 'STOP_LOSS', 'MANUAL', 'TIMEOUT'
    
    -- Performance Metrics (calculated after close)
    profit_loss_pct REAL,              -- % profit/loss
    profit_loss_amount REAL,           -- Absolute profit/loss
    holding_days INTEGER,              -- Days held
    max_profit_pct REAL,               -- Max profit reached during hold
    max_drawdown_pct REAL,             -- Max drawdown during hold
    
    created_at INTEGER DEFAULT (strftime('%s', 'now')),
    updated_at INTEGER DEFAULT (strftime('%s', 'now')),
    
    FOREIGN KEY (symbol, timeframe, timestamp) 
        REFERENCES indicators(symbol, timeframe, timestamp)
        ON DELETE CASCADE
);

-- Indexes for performance queries
CREATE INDEX IF NOT EXISTS idx_signals_symbol_time 
    ON signals(symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_type 
    ON signals(signal_type, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_strategy 
    ON signals(strategy_name, is_closed);
CREATE INDEX IF NOT EXISTS idx_signals_open 
    ON signals(is_closed, symbol) WHERE is_closed = 0;
CREATE INDEX IF NOT EXISTS idx_signals_performance 
    ON signals(is_closed, profit_loss_pct) WHERE is_closed = 1;

-- ============================================================================
-- 4. SIGNAL PERFORMANCE TABLE
-- ============================================================================
-- Tracks time-based performance of signals for analysis

CREATE TABLE IF NOT EXISTS signal_performance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id INTEGER NOT NULL,
    
    -- Time-based Performance Snapshots
    performance_1d REAL,               -- % change after 1 day
    performance_3d REAL,               -- % change after 3 days
    performance_7d REAL,               -- % change after 7 days
    performance_14d REAL,              -- % change after 14 days
    performance_30d REAL,              -- % change after 30 days
    
    -- Peak Metrics
    max_profit_pct REAL,               -- Highest profit reached
    max_profit_at INTEGER,             -- Timestamp of max profit
    max_drawdown_pct REAL,             -- Deepest drawdown
    max_drawdown_at INTEGER,           -- Timestamp of max drawdown
    
    -- Outcome Classification
    outcome TEXT,                      -- 'WIN', 'LOSS', 'BREAKEVEN'
    outcome_quality TEXT,              -- 'EXCELLENT', 'GOOD', 'POOR', 'TERRIBLE'
    
    -- Metadata
    calculated_at INTEGER DEFAULT (strftime('%s', 'now')),
    
    UNIQUE(signal_id),
    FOREIGN KEY (signal_id) REFERENCES signals(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_perf_signal 
    ON signal_performance(signal_id);
CREATE INDEX IF NOT EXISTS idx_perf_outcome 
    ON signal_performance(outcome);

-- ============================================================================
-- 5. PORTFOLIO STATE TABLE
-- ============================================================================
-- Tracks portfolio state over time for risk management

CREATE TABLE IF NOT EXISTS portfolio_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp INTEGER NOT NULL,
    
    -- Capital Tracking
    total_capital REAL NOT NULL,       -- Total capital
    available_cash REAL NOT NULL,      -- Available cash
    invested_value REAL NOT NULL,      -- Current invested value
    unrealized_pnl REAL,               -- Unrealized profit/loss
    
    -- Position Tracking
    total_positions INTEGER DEFAULT 0, -- Number of open positions
    position_details TEXT,             -- JSON: [{"symbol": "VNM", "qty": 100, "avg_price": 85000}, ...]
    
    -- Risk Metrics
    portfolio_exposure_pct REAL,       -- % of capital invested
    largest_position_pct REAL,         -- % in largest position
    diversification_score REAL,        -- 0-100 (higher = more diversified)
    
    -- Performance Metrics
    total_realized_pnl REAL,           -- Total realized P&L
    total_realized_pnl_pct REAL,       -- % return on initial capital
    win_rate REAL,                     -- % of winning trades
    sharpe_ratio REAL,                 -- Risk-adjusted return
    max_drawdown_pct REAL,             -- Maximum drawdown
    
    created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_portfolio_time 
    ON portfolio_state(timestamp DESC);

-- ============================================================================
-- 6. STRATEGY PERFORMANCE VIEWS
-- ============================================================================

-- View 1: Overall Strategy Performance Summary
CREATE VIEW IF NOT EXISTS v_strategy_performance AS
SELECT 
    strategy_name,
    signal_type,
    COUNT(*) as total_signals,
    SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END) as closed_positions,
    SUM(CASE WHEN is_closed = 0 THEN 1 ELSE 0 END) as open_positions,
    
    -- Win Rate Metrics
    ROUND(
        100.0 * SUM(CASE WHEN profit_loss_pct > 0 THEN 1 ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END), 0),
        2
    ) as win_rate_pct,
    
    -- Profit/Loss Metrics
    ROUND(AVG(CASE WHEN is_closed = 1 THEN profit_loss_pct END), 2) as avg_pnl_pct,
    ROUND(MAX(profit_loss_pct), 2) as max_win_pct,
    ROUND(MIN(profit_loss_pct), 2) as max_loss_pct,
    ROUND(SUM(CASE WHEN is_closed = 1 THEN profit_loss_pct ELSE 0 END), 2) as total_pnl_pct,
    
    -- Risk Metrics
    ROUND(AVG(CASE WHEN is_closed = 1 THEN max_drawdown_pct END), 2) as avg_max_drawdown_pct,
    ROUND(AVG(CASE WHEN is_closed = 1 THEN holding_days END), 2) as avg_holding_days,
    
    -- Quality Metrics
    ROUND(AVG(confidence_score), 2) as avg_confidence,
    ROUND(AVG(risk_reward_ratio), 2) as avg_risk_reward
    
FROM signals
WHERE strategy_name IS NOT NULL
GROUP BY strategy_name, signal_type
ORDER BY win_rate_pct DESC, total_pnl_pct DESC;

-- View 2: Indicator Combination Analysis
CREATE VIEW IF NOT EXISTS v_indicator_combination_performance AS
SELECT 
    -- Extract key conditions from reasoning JSON
    json_extract(reasoning, '$.trend_direction') as trend,
    json_extract(reasoning, '$.rsi_signal') as rsi_signal,
    json_extract(reasoning, '$.macd_trend') as macd_trend,
    json_extract(reasoning, '$.volume_signal') as volume_signal,
    
    COUNT(*) as total_signals,
    SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END) as closed_positions,
    
    -- Performance
    ROUND(
        100.0 * SUM(CASE WHEN profit_loss_pct > 0 THEN 1 ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END), 0),
        2
    ) as win_rate_pct,
    ROUND(AVG(CASE WHEN is_closed = 1 THEN profit_loss_pct END), 2) as avg_pnl_pct,
    ROUND(SUM(CASE WHEN is_closed = 1 THEN profit_loss_pct ELSE 0 END), 2) as total_pnl_pct
    
FROM signals
WHERE is_closed = 1 AND reasoning IS NOT NULL
GROUP BY trend, rsi_signal, macd_trend, volume_signal
HAVING closed_positions >= 5  -- Only show combinations with at least 5 trades
ORDER BY win_rate_pct DESC, avg_pnl_pct DESC;

-- View 3: Symbol Performance Breakdown
CREATE VIEW IF NOT EXISTS v_symbol_performance AS
SELECT 
    symbol,
    COUNT(*) as total_signals,
    SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END) as closed_positions,
    
    -- Win Rate
    ROUND(
        100.0 * SUM(CASE WHEN profit_loss_pct > 0 THEN 1 ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END), 0),
        2
    ) as win_rate_pct,
    
    -- P&L
    ROUND(AVG(CASE WHEN is_closed = 1 THEN profit_loss_pct END), 2) as avg_pnl_pct,
    ROUND(SUM(CASE WHEN is_closed = 1 THEN profit_loss_pct ELSE 0 END), 2) as total_pnl_pct,
    
    -- Best/Worst Trades
    ROUND(MAX(profit_loss_pct), 2) as best_trade_pct,
    ROUND(MIN(profit_loss_pct), 2) as worst_trade_pct,
    
    -- Latest Signal
    MAX(timestamp) as last_signal_timestamp,
    datetime(MAX(timestamp), 'unixepoch') as last_signal_date
    
FROM signals
GROUP BY symbol
ORDER BY total_pnl_pct DESC;

-- View 4: Time-Based Performance Analysis
CREATE VIEW IF NOT EXISTS v_time_performance AS
SELECT 
    strftime('%Y-%m', datetime(timestamp, 'unixepoch')) as month,
    COUNT(*) as total_signals,
    SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END) as closed_positions,
    
    -- Win Rate
    ROUND(
        100.0 * SUM(CASE WHEN profit_loss_pct > 0 THEN 1 ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END), 0),
        2
    ) as win_rate_pct,
    
    -- P&L
    ROUND(AVG(CASE WHEN is_closed = 1 THEN profit_loss_pct END), 2) as avg_pnl_pct,
    ROUND(SUM(CASE WHEN is_closed = 1 THEN profit_loss_pct ELSE 0 END), 2) as total_pnl_pct,
    
    -- Signal Distribution
    SUM(CASE WHEN signal_type = 'STRONG_BUY' THEN 1 ELSE 0 END) as strong_buy_count,
    SUM(CASE WHEN signal_type = 'WEAK_BUY' THEN 1 ELSE 0 END) as weak_buy_count
    
FROM signals
GROUP BY month
ORDER BY month DESC;

-- View 5: Risk-Reward Analysis
CREATE VIEW IF NOT EXISTS v_risk_reward_analysis AS
SELECT 
    CASE 
        WHEN risk_reward_ratio >= 3 THEN '3:1 or better'
        WHEN risk_reward_ratio >= 2 THEN '2:1 to 3:1'
        WHEN risk_reward_ratio >= 1 THEN '1:1 to 2:1'
        ELSE 'Below 1:1'
    END as risk_reward_category,
    
    COUNT(*) as total_signals,
    SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END) as closed_positions,
    
    -- Performance
    ROUND(
        100.0 * SUM(CASE WHEN profit_loss_pct > 0 THEN 1 ELSE 0 END) / 
        NULLIF(SUM(CASE WHEN is_closed = 1 THEN 1 ELSE 0 END), 0),
        2
    ) as win_rate_pct,
    ROUND(AVG(CASE WHEN is_closed = 1 THEN profit_loss_pct END), 2) as avg_pnl_pct,
    
    -- Average metrics
    ROUND(AVG(risk_reward_ratio), 2) as avg_risk_reward,
    ROUND(AVG(confidence_score), 2) as avg_confidence
    
FROM signals
WHERE risk_reward_ratio IS NOT NULL
GROUP BY risk_reward_category
ORDER BY 
    CASE risk_reward_category
        WHEN '3:1 or better' THEN 1
        WHEN '2:1 to 3:1' THEN 2
        WHEN '1:1 to 2:1' THEN 3
        ELSE 4
    END;

-- View 6: Open Positions Dashboard
CREATE VIEW IF NOT EXISTS v_open_positions AS
SELECT 
    s.id,
    s.symbol,
    s.signal_type,
    s.strategy_name,
    datetime(s.timestamp, 'unixepoch') as signal_date,
    s.execution_price,
    s.suggested_stop_loss,
    s.suggested_take_profit,
    
    -- Current performance (needs to be updated with current price)
    sp.close as current_price,
    ROUND(100.0 * (sp.close - s.execution_price) / s.execution_price, 2) as current_pnl_pct,
    
    -- Days held
    CAST((strftime('%s', 'now') - s.executed_at) / 86400 AS INTEGER) as days_held,
    
    -- Risk status
    CASE 
        WHEN sp.close <= s.suggested_stop_loss THEN 'STOP_LOSS_HIT'
        WHEN sp.close >= s.suggested_take_profit THEN 'TAKE_PROFIT_HIT'
        ELSE 'ACTIVE'
    END as position_status
    
FROM signals s
LEFT JOIN (
    SELECT symbol, close, timestamp
    FROM stock_prices
    WHERE timeframe = '1D'
    AND (symbol, timestamp) IN (
        SELECT symbol, MAX(timestamp)
        FROM stock_prices
        WHERE timeframe = '1D'
        GROUP BY symbol
    )
) sp ON s.symbol = sp.symbol
WHERE s.is_closed = 0 AND s.is_executed = 1
ORDER BY s.executed_at DESC;

-- ============================================================================
-- 7. UTILITY TRIGGERS
-- ============================================================================

-- Trigger: Auto-update updated_at timestamp
CREATE TRIGGER IF NOT EXISTS trg_signals_updated_at
AFTER UPDATE ON signals
FOR EACH ROW
BEGIN
    UPDATE signals SET updated_at = strftime('%s', 'now')
    WHERE id = NEW.id;
END;

-- Trigger: Auto-calculate holding days on close
CREATE TRIGGER IF NOT EXISTS trg_signals_calculate_holding_days
AFTER UPDATE OF is_closed ON signals
FOR EACH ROW
WHEN NEW.is_closed = 1 AND OLD.is_closed = 0
BEGIN
    UPDATE signals 
    SET holding_days = CAST((NEW.closed_at - NEW.executed_at) / 86400 AS INTEGER)
    WHERE id = NEW.id;
END;

-- ============================================================================
-- SCHEMA VERSION TRACKING
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    applied_at INTEGER DEFAULT (strftime('%s', 'now')),
    description TEXT
);

INSERT OR IGNORE INTO schema_version (version, description) 
VALUES (1, 'Initial schema with Pro Trader strategy support');

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
